name: Build All Browsers

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.14
      - run: yarn install --frozen-lockfile
      - run: bash scripts/build-all-browsers.sh
      - name: Store builds
        uses: actions/upload-artifact@v3
        with:
          path: |
            build-chrome
            build-edge
            build-firefox
            build-opera
